## Data standardization 

Data standardization is another scaling technique. In this, the mean of the feature becomes zero and the resultant distribution has a unit standard deviation(mean = 0, std = 1).

In [ ]:
#let us restore back the original dfrt 
dfrt=dfrt2.copy()
dfrt

,Item_Identifier,Item_Fat_Content,Item_Visibility,Item_Type,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,rowno,Item_Weight,Item_MRP
0,FDA15,Low Fat,0.016047,Dairy,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,0,0.282525,0.927507
1,DRC01,Regular,0.019278,Soft Drinks,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,1,0.081274,0.072068
2,FDN15,Low Fat,0.016760,Meat,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,2,0.770765,0.468288
3,FDX07,Regular,0.000000,Fruits and Vegetables,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,3,0.871986,0.640093
4,NCD19,Low Fat,0.000000,Household,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,4,0.260494,0.095805
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8428,FDF22,Low Fat,0.056783,Snack Foods,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,8518,0.137541,0.777729
8429,FDS36,Regular,0.046982,Baking Goods,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850,8519,0.227746,0.326263
8430,NCJ29,Low Fat,0.035186,Health and Hygiene,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136,8520,0.359929,0.228492
8431,FDN46,Regular,0.145221,Snack Foods,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976,8521,0.158083,0.304939
8432,DRG01,Low Fat,0.044878,Soft Drinks,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700,8522,0.610003,0.187510

In [ ]:
# data standardization with  sklearn
from sklearn.preprocessing import StandardScaler

# copy of datasets
dfrtstand = dfrt.copy()

In [ ]:
# numerical features
ncols = ['Item_Weight','Item_Visibility','Item_MRP']

# apply standardization on numerical features
for i in ncols:
    # fit on data columns
    scale = StandardScaler().fit(dfrtstand[[i]])
    # transform the data
    dfrtstand[i] = scale.transform(dfrtstand[[i]])

dfrtstand

,Item_Identifier,Item_Fat_Content,Item_Visibility,Item_Type,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,rowno,Item_Weight,Item_MRP
0,FDA15,Low Fat,-0.970363,Dairy,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,0,-0.775256,1.771968
1,DRC01,Regular,-0.907882,Soft Drinks,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,1,-1.504775,-1.483259
2,FDN15,Low Fat,-0.956579,Meat,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,2,0.994580,0.024489
3,FDX07,Regular,-1.280691,Fruits and Vegetables,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,3,1.361498,0.678265
4,NCD19,Low Fat,-1.280691,Household,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,4,-0.855115,-1.392935
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8428,FDF22,Low Fat,-0.182596,Snack Foods,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,8518,-1.300812,1.202015
8429,FDS36,Regular,-0.372130,Baking Goods,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850,8519,-0.973824,-0.515965
8430,NCJ29,Low Fat,-0.600247,Health and Hygiene,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136,8520,-0.494673,-0.888014
8431,FDN46,Regular,1.527632,Snack Foods,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976,8521,-1.226349,-0.597108
8432,DRG01,Low Fat,-0.412820,Soft Drinks,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700,8522,0.411829,-1.043966